alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -viI'
alias mkdir='mkdir -pv'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias e='${EDITOR:-nvim}'
alias v='${EDITOR:-nvim}'
alias zsource='source "${ZDOTDIR:-$HOME/.config/zsh}/.zshrc"'
alias gst='git status'
alias gl='git log'
alias gcl='git clone'
